# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_flow.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_flow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_flow.proto\"&\n\x0b\x44\x61taRequest\x12\x17\n\x06update\x18\x01 \x01(\x0b\x32\x07.Update\"/\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x06Update\x12$\n\x0ehome_utilities\x18\x01 \x03(\x0b\x32\x0c.HomeUtility\"<\n\x0bHomeUtility\x12\x10\n\x08house_id\x18\x01 \x01(\t\x12\x1b\n\tutilities\x18\x02 \x03(\x0b\x32\x08.Utility\"\x84\x01\n\x07Utility\x12\x12\n\nutility_id\x18\x01 \x01(\t\x12\x14\n\x0cutility_name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05group\x18\x05 \x01(\t\x12\x1e\n\ncomponents\x18\x06 \x03(\x0b\x32\n.Component\"P\n\tComponent\x12\x16\n\x0e\x63omponent_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\x03\x32\x33\n\x08\x44\x61taFlow\x12\'\n\x08SendData\x12\x0c.DataRequest\x1a\r.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=19
  _globals['_DATAREQUEST']._serialized_end=57
  _globals['_DATARESPONSE']._serialized_start=59
  _globals['_DATARESPONSE']._serialized_end=106
  _globals['_UPDATE']._serialized_start=108
  _globals['_UPDATE']._serialized_end=154
  _globals['_HOMEUTILITY']._serialized_start=156
  _globals['_HOMEUTILITY']._serialized_end=216
  _globals['_UTILITY']._serialized_start=219
  _globals['_UTILITY']._serialized_end=351
  _globals['_COMPONENT']._serialized_start=353
  _globals['_COMPONENT']._serialized_end=433
  _globals['_DATAFLOW']._serialized_start=435
  _globals['_DATAFLOW']._serialized_end=486
# @@protoc_insertion_point(module_scope)
